services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: registry1.dso.mil/ironbank/opensource/ollama/ollama:0.6.2
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - count: 1 # alternatively, use `count: all` for all GPUs
#              capabilities: [gpu]
#    runtime: nvidia

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: custom-open-webui:latest
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY=monkey'
      - 'VECTOR_DB=opensearch'
      - 'OPENSEARCH_URI=http://opensearch:9200'
      - 'OPENSEARCH_USERNAME=admin'
      - 'OPENSEARCH_PASSWORD=admin'
      - 'OPENSEARCH_SSL=False'
      - 'OPENSEARCH_CERT_VERIFY=False'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
  opensearch:
      image: opensearch:latest # registry1.dso.mil/ironbank/afrl-dcgs/stream/opensearch-project/opensearch:2.19.1
      container_name: opensearch
      environment:
        - cluster.name=opensearch
        - node.name=opensearch
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
        - "DISABLE_INSTALL_DEMO_CONFIG=true"
        - "DISABLE_SECURITY_PLUGIN=true"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - opensearch_data:/usr/share/opensearch/data
      ports:
        - 9200:9200
        - 9600:9600
  opensearch-dashboards:
      image: opensearchproject/opensearch-dashboards:2.19.1 # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
      container_name: opensearch-dashboards
      ports:
        - 5601:5601 # Map host port 5601 to container port 5601
      expose:
        - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
      environment:
        OPENSEARCH_HOSTS: '["http://opensearch:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
        DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true" # disables security dashboards plugin in OpenSearch Dashboards
volumes:
  ollama: {}
  open-webui: {}
  opensearch_data: {}
