apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml --out kompose/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: ollama
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ollama
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml --out kompose/
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: ollama
    spec:
      containers:
        - image: ollama/ollama:latest
          name: ollama
          ports:
            - containerPort: 11434
              protocol: TCP
          tty: true
          volumeMounts:
            - mountPath: /root/.ollama
              name: ollama
      restartPolicy: Always
      volumes:
        - name: ollama
          persistentVolumeClaim:
            claimName: ollama
