apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      initContainers:
      - name: increase-vm-max-map-count
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: opensearch
        image: "{{ .Values.opensearch.image.repository }}:{{ .Values.opensearch.image.tag }}"
        imagePullPolicy: {{ .Values.opensearch.image.pullPolicy }}
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9600
          name: transport
        env:
        {{- range $key, $value := .Values.opensearch.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.opensearch.resources.requests.memory }}
          limits:
            memory: {{ .Values.opensearch.resources.limits.memory }}
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
      volumes:
      - name: opensearch-data
        {{- if .Values.opensearch.persistence.enabled }}
        persistentVolumeClaim:
          claimName: opensearch-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}