apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  selector:
    app: opensearch
  ports:
  - name: http
    port: {{ .Values.opensearch.service.port }}
    targetPort: 9200
  - name: transport
    port: {{ .Values.opensearch.service.transportPort }}
    targetPort: 9600